version: '3'

services:
  tideways:
    image: razeware/tideways:release-v4.3.5

  application:
    environment:
      - TIDEWAYS_APIKEY=${TIDEWAYS_APIKEY}
      - TIDEWAYS_SAMPLERATE=${TIDEWAYS_SAMPLERATE:-30}
      - TIDEWAYS_COLLECT=${TIDEWAYS_COLLECT:-full}
